name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to our project! We're thrilled to have you on board. If you encounter any issues or have any questions, don't hesitate to open a new issue here. We're here to help and appreciate your contributions!"
        pr-message: "Congratulations on your first pull request! 🎉 Thank you for your contribution to our project. Our team will review your changes shortly. If you have any questions or need further assistance, feel free to reach out. We appreciate your effort and look forward to collaborating with you!"
