# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Start server
        run: |
          npm run start --if-present &
          pid=$!
          sleep 10 # Wait for the server to start (adjust the time as needed)
          if ! ps -p $pid > /dev/null; then
            echo "Server failed to start within the timeout period."
            kill -9 $pid # Terminate the process if it hasn't started successfully
            exit 1
          fi
        timeout-minutes: 5 # Set a timeout of 5 minutes for the start command
      - run: npm test
